"""Generate a Pine Script v6 overlay from a Step1Output (engine -> TradingView).

Bridge option 2 (doc/02 §3): the engine computes levels/zones/bias deterministically,
then emits a self-contained Pine snippet with the latest values HARD-CODED. Paste it
into TradingView as an indicator — it draws support/resistance, the invalidation line,
the plan's entry zone / stop / targets, and a bias label on the last bar.

Pine cannot pull an external API, so what crosses to TV is the *result* (lines/zones/
bias), never the engine. Re-run the engine and re-paste to refresh.
"""

from __future__ import annotations

import re

from .contract import Step1Output


def _f(x: float) -> str:
    return f"{float(x):.2f}"


def _safe(s: str) -> str:
    """Pine string-literal-safe: drop quotes/backslashes/newlines."""
    return re.sub(r'[\\"\n\r]', " ", str(s)).strip()


def to_pine(o: Step1Output) -> str:
    b = o.bias
    color = {"long": "color.green", "short": "color.red"}.get(b.direction, "color.gray")
    title = f"CE {o.meta.symbol} | {b.direction.upper()}"

    L: list[str] = [
        "//@version=6",
        f"// Generated by crypto-engine {o.meta.engine_version} at {o.meta.generated_at}",
        f"// {o.meta.symbol} | bias {b.direction.upper()} ({b.conviction}) | confidence {o.confidence}",
        "// Paste into TradingView. Values are hard-coded snapshots — re-run the engine to refresh.",
        f'indicator("{_safe(title)}", overlay = true)',
        "",
    ]

    if o.levels.support:
        L.append("// ── Support (nearest first) ──")
        for i, s in enumerate(o.levels.support, 1):
            L.append(f'hline({_f(s)}, "S{i}", color = color.green, linestyle = hline.style_dashed, linewidth = 1)')
        L.append("")

    if o.levels.resistance:
        L.append("// ── Resistance (nearest first) ──")
        for i, r in enumerate(o.levels.resistance, 1):
            L.append(f'hline({_f(r)}, "R{i}", color = color.red, linestyle = hline.style_dashed, linewidth = 1)')
        L.append("")

    inv = o.levels.invalidation
    L += [
        "// ── Invalidation ──",
        f'hline({_f(inv.price)}, "Invalidation", color = color.orange, linestyle = hline.style_solid, linewidth = 2)',
        f"// rule: {_safe(inv.rule)}",
        "",
    ]

    p = o.plan
    if p is not None:
        L.append("// ── Plan ──")
        if p.entry_zone and len(p.entry_zone) >= 2:
            lo, hi = sorted(p.entry_zone)[0], sorted(p.entry_zone)[-1]
            L += [
                f'e_lo = hline({_f(lo)}, "Entry lo", color = color.blue, linestyle = hline.style_dotted)',
                f'e_hi = hline({_f(hi)}, "Entry hi", color = color.blue, linestyle = hline.style_dotted)',
                "fill(e_lo, e_hi, color = color.new(color.blue, 88), title = \"Entry zone\")",
            ]
        elif p.entry_zone:
            L.append(f'hline({_f(p.entry_zone[0])}, "Entry", color = color.blue, linestyle = hline.style_dotted)')
        if p.stop is not None:
            L.append(f'hline({_f(p.stop)}, "Stop", color = color.red, linestyle = hline.style_solid, linewidth = 2)')
        for i, t in enumerate(p.targets or [], 1):
            L.append(f'hline({_f(t)}, "T{i}", color = color.teal, linestyle = hline.style_dashed)')
        if p.playbook:
            L.append(f"// playbook: {_safe(p.playbook)}")
        L.append("")

    # bias label on the last bar
    label_txt = _safe(f"BIAS {b.direction.upper()} ({b.conviction}) conf {o.confidence} | inv {_f(inv.price)}")
    L += [
        "// ── Bias label (last bar) ──",
        "if barstate.islast",
        f'    label.new(bar_index, close, "{label_txt}", xloc = xloc.bar_index, '
        f"yloc = yloc.price, style = label.style_label_left, color = {color}, "
        "textcolor = color.white, size = size.small)",
        "",
    ]
    return "\n".join(L) + "\n"
