#!/usr/bin/env python3
"""kb-synth mechanical helpers — the non-LLM parts of the Socratic-style flow.

The synthesis brain is Claude (in-session via the `kb-synth` skill). This script
only does the deterministic bits so they aren't reinvented each run:

    python kb_synth.py export <knowledge_dir> [--out Agent.md]
        Concatenate a directory's curated units into a single Agent.md that a
        downstream agent can read whole — Socratic's `export` format. Order:
        00-INDEX.md first (if present), then remaining *.md by filename.

    python kb_synth.py list <knowledge_dir>
        Show the units in a directory and their one-line titles (first H1),
        so you can see the current KB at a glance before synthesizing.

Intentionally tiny and dependency-free (stdlib only).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


def _units(knowledge_dir: Path) -> list[Path]:
    """Curated .md units in reading order: INDEX first, then the rest sorted."""
    mds = sorted(p for p in knowledge_dir.glob("*.md"))
    index = [p for p in mds if p.name.lower().startswith(("00-index", "00_index", "index"))]
    rest = [p for p in mds if p not in index]
    return index + rest


def _first_h1(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s.startswith("# "):
            return s[2:].strip()
    return "(no title)"


def cmd_export(knowledge_dir: Path, out: str) -> int:
    units = _units(knowledge_dir)
    if not units:
        print(f"no .md units in {knowledge_dir}", file=sys.stderr)
        return 1
    parts: list[str] = [
        "<!-- Generated by kb_synth.py export — curated knowledge units for a "
        "downstream agent. Edit the source units, not this file. -->",
        f"# Knowledge Base — {knowledge_dir.name}\n",
    ]
    for u in units:
        parts.append(f"\n---\n\n<!-- source: {u.name} -->\n")
        parts.append(u.read_text(encoding="utf-8").strip())
    out_path = knowledge_dir / out
    out_path.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"wrote {out_path}  ({len(units)} units)")
    return 0


def cmd_list(knowledge_dir: Path) -> int:
    units = _units(knowledge_dir)
    if not units:
        print(f"no .md units in {knowledge_dir}", file=sys.stderr)
        return 1
    for u in units:
        print(f"  {u.name:<45} {_first_h1(u)}")
    print(f"\n{len(units)} units in {knowledge_dir}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="kb-synth mechanical helpers")
    sub = ap.add_subparsers(dest="cmd", required=True)

    pe = sub.add_parser("export", help="concatenate units into Agent.md")
    pe.add_argument("knowledge_dir", type=Path)
    pe.add_argument("--out", default="Agent.md")

    pl = sub.add_parser("list", help="list units + titles")
    pl.add_argument("knowledge_dir", type=Path)

    args = ap.parse_args()
    kd: Path = args.knowledge_dir.expanduser().resolve()
    if not kd.is_dir():
        print(f"not a directory: {kd}", file=sys.stderr)
        return 2

    if args.cmd == "export":
        return cmd_export(kd, args.out)
    if args.cmd == "list":
        return cmd_list(kd)
    return 2


if __name__ == "__main__":
    sys.exit(main())
